name: Run Javascript Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    env:
      TWILIO_VIRTUAL_PHONE: ${{ secrets.TWILIO_VIRTUAL_PHONE}}
      TWILIO_NUMBER: ${{ secrets.TWILIO_NUMBER}}

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm i
          npm run build --if-present
          echo "TWILIO_VIRTUAL_PHONE=$TWILIO_VIRTUAL_PHONE" >> $GITHUB_ENV
          echo "TWILIO_NUMBER=$TWILIO_NUMBER" >> $GITHUB_ENV
          npm test
        env:
          CI: true
